# Generated by Django 4.2 on 2023-04-15 22:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('potluck', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('theme', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(max_length=200)),
                ('location_name', models.CharField(max_length=50)),
                ('street_address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(choices=[('', ''), ('alabama', 'AL'), ('alaska', 'AK'), ('arizona', 'AZ'), ('arkansas', 'AR'), ('american-samoa', 'AS'), ('california', 'CA'), ('colorado', 'CO'), ('connecticut', 'CT'), ('delaware', 'DE'), ('district-of-columbia', 'DC'), ('florida', 'FL'), ('georgia', 'GA'), ('guam', 'GU'), ('hawaii', 'HI'), ('idaho', 'ID'), ('illinois', 'IL'), ('indiana', 'IN'), ('iowa', 'IA'), ('kansas', 'KS'), ('kentucky', 'KY'), ('louisiana', 'LA'), ('maine', 'ME'), ('maryland', 'MD'), ('massachusetts', 'MA'), ('michigan', 'MI'), ('minnesota', 'MN'), ('mississippi', 'MS'), ('missouri', 'MO'), ('montana', 'MT'), ('nebraska', 'NE'), ('nevada', 'NV'), ('new-hampshire', 'NH'), ('new-jersey', 'NJ'), ('new-mexico', 'NM'), ('new-york', 'NY'), ('north-carolina', 'NC'), ('north-dakota', 'ND'), ('northern-mariana-islands', 'MP'), ('ohio', 'OH'), ('oklahoma', 'OK'), ('oregon', 'OR'), ('pennsylvania', 'PA'), ('puerto-rico', 'PR'), ('rhode-island', 'RI'), ('south-carolina', 'SC'), ('south-dakota', 'SD'), ('tennessee', 'TN'), ('texas', 'TX'), ('trust-territories', 'TT'), ('utah', 'UT'), ('vermont', 'VT'), ('virginia', 'VA'), ('virgin-islands', 'VI'), ('washington', 'WA'), ('west-virginia', 'WV'), ('wisconsin', 'WI'), ('wyoming', 'WY')], max_length=25)),
                ('zipcode', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(default='city', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='name', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='123-555-6789', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='potluck.event')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='potluck.event')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('response', models.BooleanField(default=None, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='potluck.event')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invited_to', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='host_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(fields=('event', 'guest'), name='invitation_constraints'),
        ),
    ]
