# Generated by Django 4.2 on 2023-04-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potluck', '0002_event_user_city_user_name_user_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.CharField(max_length=2),
        ),
    ]
