# Generated by Django 4.2 on 2023-04-15 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potluck', '0003_alter_event_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
