# Generated by Django 4.2 on 2023-04-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potluck', '0005_alter_item_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='street_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='zipcode',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
