# Generated by Django 4.2 on 2023-04-21 02:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('potluck', '0008_post_time_created_alter_post_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-time_created']},
        ),
    ]
