# Generated by Django 4.2 on 2023-04-21 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('potluck', '0009_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invited_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
