# Generated by Django 4.2 on 2023-04-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potluck', '0010_alter_invitation_guest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=61),
        ),
        migrations.AddField(
            model_name='user',
            name='initials',
            field=models.CharField(blank=True, max_length=3),
        ),
    ]
