# Generated by Django 4.2 on 2023-04-24 22:30

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potluck', '0011_user_full_name_user_initials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date_scheduled']},
        ),
        migrations.AddField(
            model_name='user',
            name='dietary_restrictions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('vegetarian', 'Vegetarian'), ('pescitarian', 'Pescitarian'), ('vegan', 'Vegan'), ('gluten-free', 'Gluten-Free'), ('dairy-free', 'Dairy-Free'), ('kosher', 'Kosher'), ('egg-allergy', 'Egg Allergy'), ('fish-allergy', 'Fish Allergy'), ('milk-allergy', 'Milk Allergy'), ('shellfish-allergy', 'Shellfish Allergy'), ('peanut-allergy', 'Peanut Allergy'), ('tree-nut-allergy', 'Tree Nut Allergy'), ('wheat-allergy', 'Wheat Allergy'), ('soybean-allergy', 'Soybean Allergy'), ('sesame-allergy', 'Sesame Allergy')], max_length=100), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='user',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
