# Generated by Django 4.2 on 2023-04-23 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potluck', '0011_user_full_name_user_initials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
