# Generated by Django 4.2 on 2023-04-24 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('potluck', '0011_user_full_name_user_initials'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date_scheduled']},
        ),
    ]
