# Generated by Django 4.2 on 2023-04-25 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potluck', '0015_dietaryrestriction_remove_user_dietary_restrictions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dietary_restrictions',
            field=models.ManyToManyField(blank=True, to='potluck.dietaryrestriction'),
        ),
    ]
