# Generated by Django 4.2 on 2023-04-25 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potluck', '0016_alter_user_dietary_restrictions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dietary_restrictions',
            field=models.ManyToManyField(blank=True, null=True, to='potluck.dietaryrestriction'),
        ),
    ]
