# Generated by Django 4.2 on 2023-04-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potluck', '0017_alter_user_dietary_restrictions'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='invitation',
            name='invitation_constraints',
        ),
        migrations.AddConstraint(
            model_name='invitation',
            constraint=models.UniqueConstraint(fields=('event', 'email'), name='invitation_constraints'),
        ),
    ]
