# Generated by Django 4.2 on 2023-04-25 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('potluck', '0018_remove_invitation_invitation_constraints_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['created_by']},
        ),
    ]
