# Generated by Django 4.2 on 2023-04-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potluck', '0021_alter_user_thumbnail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={'ordering': ['-event__date_scheduled']},
        ),
        migrations.AlterField(
            model_name='user',
            name='dietary_restrictions',
            field=models.ManyToManyField(blank=True, to='potluck.dietaryrestriction'),
        ),
    ]
