# Generated by Django 4.2 on 2023-04-25 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potluck', '0022_alter_invitation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dietary_restrictions',
            field=models.ManyToManyField(blank=True, related_name='user', to='potluck.dietaryrestriction'),
        ),
    ]
