# Generated by Django 4.2 on 2023-04-26 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('potluck', '0023_alter_user_dietary_restrictions'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='invitation',
            options={'ordering': ['event__date_scheduled']},
        ),
    ]
