# Generated by Django 4.2 on 2023-04-26 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('potluck', '0024_alter_invitation_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date_scheduled']},
        ),
    ]
