# Generated by Django 4.2 on 2023-04-27 12:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('potluck', '0027_event_tip_jar'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='invite_code',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, null=True),
        ),
    ]
