# Generated by Django 4.2 on 2023-04-27 12:59

from django.db import migrations
import uuid


def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("potluck", "Event")
    for row in MyModel.objects.all():
        row.invite_code = uuid.uuid4()
        row.save(update_fields=["invite_code"])


class Migration(migrations.Migration):

    dependencies = [
        ('potluck', '0028_event_invite_code'),
    ]

    operations = [
        # omit reverse_code=... if you don't want the migration to be reversible.
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
