# Generated by Django 4.2 on 2023-04-27 12:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('potluck', '0029_auto_20230427_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='invite_code',
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
