# Generated by Django 4.2 on 2023-04-27 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potluck', '0030_auto_20230427_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='email',
            field=models.EmailField(blank=True, max_length=100),
        ),
    ]
