# Generated by Django 4.2 on 2023-04-27 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potluck', '0031_alter_invitation_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_acquired',
            field=models.BooleanField(default=False),
        ),
    ]
