# Generated by Django 4.2 on 2023-04-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potluck', '0032_item_is_acquired'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='dietary_restrictions',
            field=models.ManyToManyField(blank=True, related_name='item', to='potluck.dietaryrestriction'),
        ),
    ]
