# Generated by Django 4.2 on 2023-04-28 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potluck', '0034_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='playlist_link',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
