# Generated by Django 4.2 on 2023-04-28 22:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('potluck', '0037_alter_notification_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='invitation',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='item',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='post',
        ),
        migrations.AlterField(
            model_name='notification',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='potluck.event'),
        ),
    ]
